$:.unshift(File.expand_path("../", __FILE__))
require "aws_inventory/version"
require "text-table"
require "active_support/all"

module AwsInventory
  autoload :Base, "aws_inventory/base"
  autoload :Help, "aws_inventory/help"
  autoload :Command, "aws_inventory/command"
  autoload :CLI, "aws_inventory/cli"
  autoload :AwsServices, "aws_inventory/aws_services"
  autoload :Shared, "aws_inventory/shared"
  autoload :Presenter, "aws_inventory/presenter"
  autoload :Cfn, "aws_inventory/cfn"
  autoload :Ec2, "aws_inventory/ec2"
  autoload :Vpc, "aws_inventory/vpc"
  autoload :SecurityGroup, "aws_inventory/security_group"
  autoload :Rds, "aws_inventory/rds"
  autoload :Route53, "aws_inventory/route53"
  autoload :Acm, "aws_inventory/acm"
  autoload :Elb, "aws_inventory/elb"
  autoload :Eb, "aws_inventory/eb"
  autoload :Ecs, "aws_inventory/ecs"
  autoload :Keypair, "aws_inventory/keypair"
  autoload :Iam, "aws_inventory/iam"
  autoload :Cloudwatch, "aws_inventory/cloudwatch"
end
